#!/usr/bin/env python
# -*- coding:utf-8 -*-

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def Fibonacci(num):
    a, b = 0, 1
    while b < num:
        yield a + b
        a, b = b, a + b

def IsEven(num):
    return not (num % 2)

def SumEvenFibonacci(num):
    next(Fibonacci(num) for i in range(num))

if __name__ == '__main__':
    print(SumEvenFibonacci(4000000))
