#/bin/bash
#Each new term in the Fibonacci sequence is generated by adding the previous two
#terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

sum_fib_even() {
    _res=0
    _s=0
    _t=1
    while [ $_t -lt 4000000 ]
    do
        _tmp=$_s
        _s=$_t
        _t=`expr $_t + $_tmp`
        if [ `expr $_s % 2` -eq 0 ]; then
            _res=`expr $_res + $_s`
        fi
    done
    echo $_res
}

sum_fib_even
