#!/bin/bash
#Each new term in the Fibonacci sequence is generated by adding the previous two
#terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

ans=0; s=0; t=1
while [ $t -lt 4000000 ]
do
    tmp=$s
    s=$t
    let t+=$tmp
    if [ $(($s % 2)) -eq 0 ]; then
        let ans+=$s
    fi
done

echo $ans

