#!/bin/bash
:<<'###'
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
###

function fib() {
    local {s=0,t=1,tmp}
    while [ $t -lt $1 ]
    do
        tmp=$s; s=$t
        let t+=$tmp
        echo $s
    done
}

fib 4000000 | grep '[02468]$' | paste -s | sed -e 's/\s/+/g' | bc

