/*
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

var hexagonal = (function() {
  var n = 0;
  return function() {
    n++;
    return n * (2 * n - 1);
  };
}());

var isTriangle = function(n) {
  var res = (Math.sqrt(8 * n + 1) - 1) / 2;
  return res === Math.floor(res);
};

var isPentagonal = function(n) {
  var res = (Math.sqrt(24 * n + 1) + 1) / 6;
  return res === Math.floor(res);
};

hexagonal();
console.log((function() {
  for (;;) {
    var x = hexagonal();
    if (isTriangle(x) && isPentagonal(x) && x !== 40755) {
      return x;
    }
  }
}()));

