/*
Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
difference is pentagonal and D = |P[k] − P[j]| is minimised; what is the value
of D?
*/

var penta = (function() {
  var n = 0;
  return function() {
    n++;
    return n * (3 * n - 1) / 2;
  };
}());

var isPentagonal = function(n) {
  var res = (Math.sqrt(24 * n + 1) + 1) / 6;
  return res === Math.floor(res);
};

var cache = [];
var ans;
while (!ans) {
  var curr = penta();
  var i;
  for (i=0, len=cache.length; i<len; i++) {
    if ([curr - cache[i], curr + cache[i]].every(isPentagonal)) {
      ans = curr - cache[i];
    }
  }
  cache.unshift(curr);
}

console.log(ans);

