/*
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
*/

function divisors(n) {
	var res = [];
	for(var i=1; i<Math.sqrt(n); i++) {
		if(n%i==0) {
			res.push(i);
			res.push(n/i);
		}
	}
	return res;
}

var i = 1;
var tri = 1;
while(divisors(tri).length < 500) {
	i += 1;
	tri = i * (i + 1) / 2;
}
console.log(tri)
