/*
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
*/
/*
var divisors = function(n) {
	var res = [], i, lim;
	for (i=1, lim=Math.sqrt(n); i<lim; i++) {
    if (n % i === 0) {
      res.push(i, n / i);
    }
	}
	return res;
};
*/
function factorize(n) {
  var res = {};
  while (n % 2 === 0) {
    res[2] = (res[2] || 0) + 1;
    n /= 2;
  }

  var d = 3;
  while (n >= d) {
    if (n % d) {
      d += 2;
    } else {
      res[d] = (res[d] || 0) + 1;
      n /= d;
    }
  }
  return res;
}


function divisors(n) {
  var factors = factorize(n),
      res = 1;
  for (var i in factors) {
    res *= (Number(factors[i]) + 1);
  }
  return res;
}


var tri = (function() {
  var i = 0;
  return function() {
    i ++;
    return i * (i + 1) / 2;
  };
}());

console.log((function() {
  var x;
  while (divisors(x) < 500) {
    x = tri();
  }
  return x;
}()));

