/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function sumEvenFib(max) {
  var res = 0;
  var s = 1;
  var t = 1;
  while (t < max) {
    var tmp = s;
    s = t;
    t += tmp;
    if (s % 2 == 0) {
      res += s
    }
  }
  return res;
}

console.log(sumEvenFib(4000000))
