/*
 * Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first ten
 * pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
 * difference, 70 − 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
 * difference is pentagonal and D = |P[k] − P[j]| is minimised; what is the value
 * of D?
 */

function *generatePentagonals() {
  let n = 0
  while (true) {
    n++
    yield n * (3 * n - 1) / 2
  }
}

function isPentagonal(n) {
  return (((24 * n + 1) ** 0.5 + 1) / 6) % 1 == 0
}

const cache = []
let answer
loop: for (const pentagonal of generatePentagonals()) {
  for (let i = 0, len = cache.length; i < len; i++) {
    if (isPentagonal(pentagonal - cache[i]) && isPentagonal(pentagonal + cache[i])) {
      answer = pentagonal - cache[i]
      break loop
    }
  }
  cache.push(pentagonal)
}
console.log(answer)
