SRCS := $(wildcard Problem*.c)
EXECUTABLES := $(SRCS:.c=)

.PHONY: all build clean

all: build

build: $(EXECUTABLES)

clean:
	rm -f $(EXECUTABLES)

EXECUTABLES: $(SRCS)

Problem2-1: Problem2-1.c
	$(CC) $< -lm -o $@

Problem4: Problem4.c
	$(CC) $< -lm -o $@

Problem7: Problem7.c
	$(CC) $< -lm -o $@

Problem9: Problem9.c
	$(CC) $< -lm -o $@

Problem10: Problem10.c
	$(CC) $< -lm -o $@

Problem11: Problem11.c
	$(CC) $< -lm -o $@

Problem16: Problem16.c
	$(CC) $< -lgmp -o $@

Problem20: Problem20.c
	$(CC) $< -lgmp -o $@

Problem21: Problem21.c
	$(CC) $< -lm -o $@

Problem27: Problem27.c
	$(CC) $< -lm -o $@

Problem29: Problem29.c
	$(CC) $< -lm -o $@

Problem38: Problem38.c
	$(CC) $< -lm -o $@

Problem41: Problem41.c
	$(CC) $< -lm -o $@

Problem42: Problem42.c
	$(CC) $< -lm -o $@

Problem43: Problem43.c
	$(CC) $< -lm -o $@

Problem44: Problem44.c
	$(CC) $< -lm -o $@

Problem104: Problem104.c
	$(CC) $< -lm -o $@

