/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <math.h>
#include <stdio.h>

static const double SQRT5 = 2.2360679775;
static const double PHI = 1.61803398875;

double fibterm(int n) {
    return round(pow(PHI, n + 1) / SQRT5);
}

int main(int argc, char **argv) {
    int sum = 0;
    int i, x;
    for (i = 2; (x = (int)fibterm(i)) < 4e6; i += 3) {
        sum += x;
    }
    printf("%d\n", sum);
    return 0;
}
