/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdlib.h>

long *fibonacci(long limit, size_t *size) {
    long s = 0;
    long t = 1;
    long u;
    long *res = (long *)calloc(0, sizeof(long));
    while (t < limit) {
        u = s;
        s = t;
        t += u;
        *size += 1;
        res = realloc(res, *size * sizeof(long));
        res[*size - 1] = s;
    }
    return res;
}

int main(int argc, char const* argv[])
{
    const long limit = 4000000;
    size_t size;
    long *fib = fibonacci(limit, &size);
    int i;
    long res = 0;
    for (i = 0; i < size; i++) {
        if (fib[i] % 2 == 0) {
            res += fib[i];
        }
    }
    printf("%ld\n", res);
    free(fib);
    return 0;
}

