/* Even Fibonacci numbers
 *
 * Problem 2 [icon_info]Published on Friday, 19th October 2001, 06:00 pm; Solved
 * by 623501;
 * Difficulty rating: 5%
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two
 * terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

WITH RECURSIVE fibonacci (i, j)
AS (
  SELECT 1, 1
  UNION ALL
  SELECT j, i + j FROM fibonacci
  WHERE i < 4000000
)
SELECT SUM(i)
FROM fibonacci
WHERE i % 2 = 0;
