/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
 * Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
 * Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
 *
 * It can be verified that T[285] = P[165] = H[143] = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

import java.util.stream.IntStream;

public class Problem45 {
    private static class Triangulars {
        private Triangulars() {
        }

        public static int at(int n) {
            return n * (n * 2 - 1);
        }

        public static IntStream intStream() {
            return IntStream.iterate(1, x -> x + 1).map(Triangulars::at);
        }
    }

    private static class Pentagonals {
        private Pentagonals() {
        }

        public static boolean isPentagonal(int x) {
            return ((Math.sqrt(24 * x + 1) + 1) / 6) % 1 == 0;
        }
    }

    public static void main(String[] args) {
        int answer = Triangulars.intStream()
                .skip(1)
                .filter(Pentagonals::isPentagonal)
                .findFirst()
                .getAsInt();
        System.out.println(answer);
    }
}
