/*
 * Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first ten
 * pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
 * difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
 * difference are pentagonal and D = |P[k] − P[j]| is minimised; what is the value
 * of D?
 */

import java.util.ArrayList;
import java.util.List;
import java.util.PrimitiveIterator;

public class Problem44 {
    private static class Pentagonal implements Iterable<Integer> {
        public static boolean isPentagonal(int x) {
            return ((Math.sqrt(24 * x + 1) + 1) / 6) % 1 == 0;
        }

        @Override
        public PrimitiveIterator.OfInt iterator() {
            return new PentagonalIterator();
        }

        private static class PentagonalIterator implements PrimitiveIterator.OfInt {
            private int n = 1;

            @Override
            public boolean hasNext() {
                return true;
            }

            @Override
            public int nextInt() {
                int result = n * (3 * n - 1) / 2;
                n++;
                return result;
            }
        }
    }

    public static void main(String[] args) {
        List<Integer> cache = new ArrayList<>();
        Pentagonal pentagonal = new Pentagonal();
        int answer = 0;
        loop: {
            for (int x : pentagonal) {
                for (int y : cache) {
                    if (Pentagonal.isPentagonal(x - y) && Pentagonal.isPentagonal(x + y)) {
                        answer = x - y;
                        break loop;
                    }
                }
                cache.add(x);
            }
        }
        System.out.println(answer);
    }
}

