/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

class Problem2 {
	public static int sumEvenFib(int max) {
		int s = 1;
		int t = 1;
		int tmp = 0;
		int res = 0;
		while(t<max) {
			tmp = s;
			s = t;
			t += tmp;
			if(s % 2 == 0) {
				res += s;
			}
		}
		return res;
	}
	public static void main(String args[]) {
		System.out.println(sumEvenFib(4000000));
	}
}
