;;; Each new term in the Fibonacci sequence is generated by adding the previous two
;;; terms. By starting with 1 and 2, the first 10 terms will be:
;;;
;;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;;
;;; By considering the terms in the Fibonacci sequence whose values do not exceed
;;; four million, find the sum of the even-valued terms.

(define (fibonacci-upto limit)
  (let loop ((i 0)
             (j 1))
    (if (>= j limit)
        (list i)
        (cons i (loop j (+ i j))))))

(display (apply +
                (filter even?
                        (fibonacci-upto 4e6))))
(newline)
