;;; Triangle, pentagonal, and hexagonal numbers are generated by the following
;;; formulae:
;;;
;;; Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
;;; Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
;;; Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
;;;
;;; It can be verified that T[285] = P[165] = H[143] = 40755.
;;;
;;; Find the next triangle number that is also pentagonal and hexagonal.

(import (srfi :41))

(define (pentagonal? x)
  (integer? (/ (1+ (sqrt (1+ (* 24 x))))
               6)))

(define (hexagonal-at n)
  (* n (+ n n -1)))

(define-stream (hexagonal-stream)
               (stream-map hexagonal-at
                           (stream-from 0)))

(display
  (stream-ref (stream-filter pentagonal?
                             (hexagonal-stream))
              2))
(newline)
