/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/
                                                           
#include <iostream>
using namespace std;

int fib(int n) {
	return n < 2 ? 1 : fib(n - 1) + fib(n - 2);
}

int main(int argc, char const* argv[]) {
	int x = 0;
	int ans = 0;
	for (int i=0; x<4e6; x=fib(i), i++) {
		ans += x % 2 ? 0 : x;
	}
	cout << ans;
	return 0;
}
