###
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
###

fibonacci = ->
	[i, j] = [0, 1]
	-> ([_, i, j] = [i, j, i + j])[0]
fib = fibonacci()

ans = 0
while (i = fib()) < 4000000
	ans += i; fib(); fib()

console.log(ans)

