###
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
###

hexagonal = do (n=0) -> -> ++ n * (2 * n - 1)

isPentagonal = (n) ->
	(res = (Math.sqrt(24 * n + 1) + 1) / 6) == Math.floor(res)


hexagonal()
(x until (x = hexagonal()) and isPentagonal(x)) for i in [0, 1]
console.log x

