###
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
###

fib = (n) -> if n < 2 then 1 else fib(n - 2) + fib(n - 1)

i = res = ans = 0
while res < 4000000
	res = fib(i)
	if res % 2 == 0 then ans += res
	i++

console.log(ans)

