/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
 * Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
 * Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
 *
 * It can be verified that T[285] = P[165] = H[143] = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
package main

import (
	"fmt"
	"math"
)

func IsPentagonal(x int) bool {
	_, fractional := math.Modf((math.Sqrt(24.0*float64(x)+1) + 1.0) / 6.0)
	return fractional == 0.0
}

func HexagonalAt(n int) int {
	return n * (n*2 - 1)
}

func main() {
	for i := 0; ; i++ {
		x := HexagonalAt(i)
		if x > 40755 && IsPentagonal(x) {
			fmt.Println(x)
			break
		}
	}
}
