/*
 * Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first ten
 * pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
 * difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
 * difference are pentagonal and D = |P[k] − P[j]| is minimised; what is the value
 * of D?
 */
package main

import (
	"fmt"
	"math"
)

func PentagonalAt(n int) int {
	return n * (3*n - 1) >> 1
}

func IsPentagonal(x int) bool {
	_, fractional := math.Modf((math.Sqrt(24.0*float64(x)+1.0) + 1.0) / 6.0)
	return fractional == 0.0
}

func main() {
	cache := make([]int, 0)
	for i := 0; ; i++ {
		x := PentagonalAt(i)
		for j := i - 1; j > 0; j-- {
			y := cache[j]
			if IsPentagonal(x-y) && IsPentagonal(x+y) {
				fmt.Println(x - y)
				return
			}
		}
		cache = append(cache, x)
	}
}
