#|
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
|#

(define (fib n)
  (if (< n 2)
    1
    (+ (fib (- n 1)) (fib (- n 2)))))

(define (loop n res)
  (define val (fib n))
  (if (> val 4000000)
    res
    (if (= 0 (remainder val 2))
      (loop (+ n 1) (+ val res))
      (loop (+ n 1) res))))

(display (loop 0 0))

