#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle           Tn=n(n+1)/2           1, 3, 6, 10, 15, ...
Pentagonal           Pn=n(3n?1)/2           1, 5, 12, 22, 35, ...
Hexagonal           Hn=n(2n?1)           1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

from math import sqrt
from itertools import count

def is_pentagonal(n):
    return not (sqrt(24 * n + 1) + 1) / 6 % 1

def gen_hexagonal():
    for i in count():
        yield i * (2 * i - 1)

if __name__ == '__main__':
    for i in gen_hexagonal():
        if is_pentagonal(i) and i > 40755:
            print i
            break

