#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle           Tn=n(n+1)/2           1, 3, 6, 10, 15, ...
Pentagonal           Pn=n(3n?1)/2           1, 5, 12, 22, 35, ...
Hexagonal           Hn=n(2n?1)           1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
def genTri(max):
    res = 0
    for i in range(1, max):
        res += i
        yield res

def genPen(max):
    res = 0
    for i in range(1, max, 3):
        res += i
        yield res

def genHex(max):
    res = 0
    for i in range(1, max, 4):
        res += i
        yield res

if __name__ == '__main__':
    tri = set(i for i in genTri(1000000))
    pen = set(i for i in genPen(1000000))
    hex = set(i for i in genHex(1000000))

    print tri & pen & hex

