# coding:utf-8
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from itertools import takewhile

def fib():
    s, t = 0, 1
    while True:
        s, t = t, s + t
        yield s

print sum(i for i in takewhile(lambda x: x < 4e6, fib()) if not i % 2)

