#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?
'''

from itertools import count
from math import sqrt

def gen_pentagonal(m=0):
    for n in count(1):
        res = n * (3 * n - 1) / 2
        if m and res > m: return
        yield res

def is_pentagonal(n):
    return (sqrt(24 * n + 1) + 1) / 6 % 1 == 0


if __name__ == '__main__':
    penta = gen_pentagonal()
    ans = None
    cache = []
    while not ans:
        curr = next(penta)
        for i in cache:
            if all(map(is_pentagonal, [curr - i, curr + i])):
                ans = curr - i
        cache = [curr] + cache
    print ans

