/*
Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
difference is pentagonal and D = |P[k] − P[j]| is minimised; what is the value
of D?
*/

object Problem44 {
  val pentagonal = Stream.from(1).map(n => n*(3*n-1)/2)

  def isPentagonal(x:Int) = ((math.sqrt(1+24*x)+1)/6) % 1 == 0

  def main(args:Array[String]) {
    val (k, j) = pentagonal
      .flatMap(x => pentagonal.takeWhile(x>)
        .map(_ match {
          case y if(isPentagonal(x+y) && (isPentagonal(x-y))) => (x, y)
          case y => null
          }
        )
      ).filter(null!=).head
    println(k - j)
  }
}

