//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

object Problem2 {
  def fibonacci(max:Int, s:Int = 0, t:Int = 1, acc:Int = 0):Int = {
    if(s > max) acc else {
      if(s % 2 == 0) {
      fibonacci(max, t, s + t, acc + s)
      }
      else {
      fibonacci(max, t, s + t, acc)
      }
    }
  }
  def main(args:Array[String]) {
    println(fibonacci(4000000))
  }
}
