#!/usr/bin/env perl
# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

use strict;
use warnings;
use Memoize;

memoize('fib');
sub fib {
    my $n = shift;
    return 1 if $n < 2;
    return fib($n - 1) + fib($n - 2);
}

my $acc = 0;
for (my $i = 2; (my $x = fib($i)) < 4e6; $i += 3) {
    $acc += $x;
}
print($acc . "\n");

