#!/usr/bin/env perl
# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
# Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
# Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
# Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
#
# It can be verified that T[285] = P[165] = H[143] = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

use strict;
use warnings;

sub is_pentagonal {
    my $x = shift;

    my $a = (sqrt(24 * $x + 1) + 1) / 6;
    return $a == int($a);
}

sub hexagonal {
    my $n = shift;

    return $n * ($n * 2 - 1);
}

my $x = 0;
for (my $i = 0;; $x = hexagonal(++$i)) {
    if ($x > 40755 and is_pentagonal($x)) {
        print "$x\n";
        last;
    }
}
