#!/usr/bin/env perl -l
=pod
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
=cut

use strict;
use warnings;

sub fib {
    my ($i, $j) = (0, 1);
    return sub {
        return (($i, $j) = ($j, $i + $j))[0];
    }
}

my ($fib, $x, $ans) = (fib(), 0, 0);
$ans += $x % 2 ? 0 : $x while ($x = $fib -> ()) < 4e6;
print $ans;

