<?php
/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
 * Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
 * Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
 *
 * It can be verified that T[285] = P[165] = H[143] = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

function isPentagonal($x) {
    return !fmod((sqrt(24 * $x + 1) + 1) / 6, 1);
}

function hexagonals() {
    for ($i = 0; $i != INF; $i++) {
        yield $i * (2 * $i - 1);
    }
}

foreach (hexagonals() as $i) {
    if (isPentagonal($i) and $i > 40755) {
        break;
    }
}
echo $i;

